title: Deborah L. Haar
logo: "/images/Haar-circle.jpg?raw=true"
description: >
  Philosopher of science and <br>
  Data enthusiast
  <br><br>
  My interest in data ranges from big picture philosophical issues such as the evaluation and justification of models to hands-on cleaning and manipulation, visualization, and analysis.
  
  <br><br>
  Skills:<br>
  Python, Pandas, NumPy, SQL, Tableau, Excel, HTML
  <br>
  Data importing, cleaning, manipulation, visualization
  <br><br>
  
  <a href="https://www.linkedin.com/in/deborahlhaar" target = "_blank" rel=" noopener noreferrer">My LinkedIn Profile</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-186710624-1



