title: Deborah L. Haar
logo: "/images/Haar-circle.jpg?raw=true"
description: >
  <br><br>
  Project portfolio
  <br><br>
  
  <a href="https://www.linkedin.com/in/deborahlhaar" target = "_blank" rel=" noopener noreferrer">My LinkedIn Profile</a>
  
  
theme: jekyll-theme-minimal
google_analytics: G-G52TWZV9ZB



