title: Deborah L. Haar
logo: "/images/Haar-circle.jpg?raw=true"
description: >
  Project portfolio
  <br><br>
  
  <a href="https://www.linkedin.com/deborahlhaar">My LinkedIn Profile</a>
  
  
theme: jekyll-theme-minimal



