title: Deborah L. Haar
logo: "/images/Haar-circle.jpg?raw=true"
description: >
  Philosopher, Data enthusiast, Civic tech
  
  Project portfolio
  <br><br>
  
  <a href="https://www.linkedin.com/in/deborahlhaar" target = "_blank" rel=" noopener noreferrer">My LinkedIn Profile</a>
  
  
theme: jekyll-theme-minimal



